### ISSUE TITLE
Просто почитать

### ISSUE THREAD

**Issue by SimonOsipov** [sergiishevchenko/LearnPythonCourse#17]
https://github.com/sergiishevchenko/LearnPythonCourse/blob/bec7c5ba364119daa30bd38bb7ac88e1a56fe9db/Homework%232/csv-task.py#L8

https://docs.python.org/3/library/functions.html?highlight=open#open

Почитай документацию про `open()`, а точнее раздел про `newline` и чем может грозить использование `newline=''` =)

**Comment by sergiishevchenko** [comment]
http://joxi.ru/MAjk3edCjD4Kqr  я понял. больше не буду)
