### ISSUE TITLE
Усложним задачу?

### ISSUE THREAD

**Issue by SimonOsipov** [sergiishevchenko/LearnPythonCourse#18]
https://github.com/sergiishevchenko/LearnPythonCourse/blob/bec7c5ba364119daa30bd38bb7ac88e1a56fe9db/Homework%232/datetime-task.py#L9

А давай попробуем тут вместо в лоб -30 дней все таки отнять relative 1 месяц. То есть учитывая годовые особенности (февраль, високосные года, 30 и 31 день в месяце) 

Это задача на подумать и погуглить. В общем чате, кстати, про это спрашивали.

**Comment by sergiishevchenko** [comment]
пофиксил. вроде так
https://github.com/sergiishevchenko/LearnPythonCourse/blob/master/Homework%232/datetime-task.py
