### ISSUE TITLE
Порядок команд

### ISSUE THREAD

**Issue by SimonOsipov** [sergiishevchenko/LearnPythonCourse#4]
https://github.com/sergiishevchenko/LearnPythonCourse/blob/719953bf2d35cb0bd0dc036f973fd4dd0c2fad83/Homework%231/ephem_bot.py#L48

В виду особенностей работы `handlers`, правильным будет инициализация `handlers` от наиболее частных к наиболее общим.

**Comment by sergiishevchenko** [comment]
http://joxi.ru/V2VMDv6sdOvnwm как-то так?
