### ISSUE TITLE
.DS_Store в репозитории

### ISSUE THREAD

**Issue by SimonOsipov** [sergiishevchenko/LearnPythonCourse#5]
DS_Store – это файлы, используемые Mac OS X для хранения особых метаданных о родительских папках. Они создаются в каждой папке, к которой Mac OS X Finder получает доступ, включая сетевые тома и внешние диски.

Он не нужен в репозитории, добавь в гитигнор

**Comment by sergiishevchenko** [comment]
ok занёс
